<template>
  <div id="cont">
    <ul>
      <li>热销榜</li>
      <li class="a"><span>
        <span></span>单人特色套餐
      </span></li>
      <li>特色粥品</li>
      <li>精选热菜</li>
      <li>爽口凉菜</li>
      <li>半成品</li>
      <li>饭类</li>
      <li>面类</li>
    </ul>
    <div>
      <ul>
        <li>单人特色套餐</li>
        <li>
          <div>
            <div>图片</div>
            <div>
              <p>皮蛋瘦肉粥配包子套餐</p>
              <p>咸粥</p>
              <p>月售1132份&nbsp;好评率100%</p>
              <div>
                <p>
                  <span>￥24</span>
                  <span>￥28</span>
                </p>
                <div>
                  <p>-</p>
                  <p>1</p>
                  <p>+</p>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
      <ul>
        <li>特色粥品</li>
        <li>
          <div>
            <div>图片</div>
            <div>
              <p>莲子核桃黑米粥</p>
              <p></p>
              <p>月售1132份&nbsp;好评率100%</p>
              <div>
                <p>
                  <span>￥10</span>
                  <span></span>
                </p>
                <div>
                  <p>-</p>
                  <p>1</p>
                  <p>+</p>
                </div>
              </div>
            </div>
          </div>
        </li>
        <li>
        <div>
          <div>图片</div>
          <div>
            <p>雪梨银耳百合粥</p>
            <p></p>
            <p>月售1132份&nbsp;好评率100%</p>
            <div>
              <p>
                <span>￥24</span>
                <span></span>
              </p>
              <div>
                <p>-</p>
                <p>1</p>
                <p>+</p>
              </div>
            </div>
          </div>
        </div>
      </li>
        <li>
          <div>
            <div>图片</div>
            <div>
              <p>南瓜粥</p>
              <p></p>
              <p>月售1132份&nbsp;好评率100%</p>
              <div>
                <p>
                  <span>￥24</span>
                  <span></span>
                </p>
                <div>
                  <p>-</p>
                  <p>1</p>
                  <p>+</p>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</template>


<style lang="scss" scoped>
  @import "./cont.scss";
</style>
